import os

# List of files to remove (copy-paste from your CSV or list)
FILES_TO_REMOVE = [
    "checklists/README.md",
    # "checklists/level3/python/api.md",
    "checklists/level3/python/platform.md",
    # "checklists/level3/python/integration.md",
    "checklists/level3/python/devtools.md",
    "checklists/level3/python/qa.md",
    "checklists/level3/python/devsecops.md",
    # "checklists/level3/python/data.md",
    # "checklists/level3/python/general.md",
    # "checklists/level3/python/backend.md",
    "checklists/level3/python/observability.md",
    "checklists/level3/python/frontend.md",
    "checklists/level3/python/mobile.md",
    # "checklists/level3/python/security.md",
    # "checklists/level3/python/mlops.md",
    # "checklists/level3/general/platform.md",
    "checklists/level3/general/qa.md",
    # "checklists/level3/java/api.md",
    "checklists/level3/java/platform.md",
    "checklists/level3/java/qa.md",
    "checklists/level3/java/devsecops.md",
    # "checklists/level3/java/data.md",
    "checklists/level3/java/general.md",
    # "checklists/level3/java/observability.md",
    # "checklists/level3/java/mobile.md",
    # "checklists/level3/java/security.md",
    "checklists/level3/java/mlops.md",
    # "checklists/level3/csharp/api.md",
    "checklists/level3/csharp/platform.md",
    # "checklists/level3/csharp/integration.md",
    "checklists/level3/csharp/devtools.md",
    "checklists/level3/csharp/qa.md",
    "checklists/level3/csharp/devsecops.md",
    # "checklists/level3/csharp/data.md",
    # "checklists/level3/csharp/general.md",
    # "checklists/level3/csharp/backend.md",
    # "checklists/level3/csharp/observability.md",
    # "checklists/level3/csharp/frontend.md",
    # "checklists/level3/csharp/mobile.md",
    # "checklists/level3/csharp/security.md",
    "checklists/level3/csharp/mlops.md",
    # "checklists/level3/javascript/api.md",
    "checklists/level3/javascript/platform.md",
    # "checklists/level3/javascript/qa.md",
    "checklists/level3/javascript/devsecops.md",
    # "checklists/level3/javascript/data.md",
    # "checklists/level3/javascript/general.md",
    # "checklists/level3/javascript/observability.md",
    # "checklists/level3/javascript/mobile.md",
    # "checklists/level2/python/api.md",
    "checklists/level2/python/platform.md",
    # "checklists/level2/python/integration.md",
    "checklists/level2/python/devtools.md",
    "checklists/level2/python/qa.md",
    "checklists/level2/python/devsecops.md",
    "checklists/level2/python/data.md",
    # "checklists/level2/python/general.md",
    # "checklists/level2/python/backend.md",
    # "checklists/level2/python/observability.md",
    "checklists/level2/python/frontend.md",
    "checklists/level2/python/mobile.md",
    # "checklists/level2/python/security.md",
    # "checklists/level2/python/mlops.md",
    "checklists/level2/general/platform.md",
    # "checklists/level2/general/qa.md",
    # "checklists/level2/general/data.md",
    "checklists/level2/java/platform.md",
    # "checklists/level2/java/integration.md",
    # "checklists/level2/java/qa.md",
    "checklists/level2/java/devsecops.md",
    # "checklists/level2/java/data.md",
    # "checklists/level2/java/backend.md",
    # "checklists/level2/java/observability.md",
    # "checklists/level2/java/mobile.md",
    "checklists/level2/java/mlops.md",
    # "checklists/level2/csharp/api.md",
    "checklists/level2/csharp/platform.md",
    # "checklists/level2/csharp/integration.md",
    "checklists/level2/csharp/devtools.md",
    # "checklists/level2/csharp/qa.md",
    "checklists/level2/csharp/devsecops.md",
    "checklists/level2/csharp/data.md",
    # "checklists/level2/csharp/general.md",
    # "checklists/level2/csharp/backend.md",
    # "checklists/level2/csharp/observability.md",
    # "checklists/level2/csharp/frontend.md",
    # "checklists/level2/csharp/mobile.md",
    # "checklists/level2/csharp/security.md",
    "checklists/level2/csharp/mlops.md",
    # "checklists/level2/javascript/api.md",
    "checklists/level2/javascript/platform.md",
    # "checklists/level2/javascript/integration.md",
    "checklists/level2/javascript/devtools.md",
    # "checklists/level2/javascript/qa.md",
    "checklists/level2/javascript/devsecops.md",
    "checklists/level2/javascript/data.md",
    # "checklists/level2/javascript/general.md",
    # "checklists/level2/javascript/backend.md",
    # "checklists/level2/javascript/observability.md",
    # "checklists/level2/javascript/mobile.md",
    "checklists/level2/javascript/mlops.md",
    "checklists/.obsidian/workspace.json",
    "checklists/.obsidian/app.json",
    "checklists/.obsidian/core-plugins.json",
    "checklists/.obsidian/appearance.json",
    # "checklists/level1/python/api.md",
    "checklists/level1/python/platform.md",
    # "checklists/level1/python/integration.md",
    "checklists/level1/python/devtools.md",
    "checklists/level1/python/qa.md",
    "checklists/level1/python/devsecops.md",
    # "checklists/level1/python/data.md",
    # "checklists/level1/python/general.md",
    # "checklists/level1/python/backend.md",
    # "checklists/level1/python/observability.md",
    "checklists/level1/python/frontend.md",
    "checklists/level1/python/mobile.md",
    # "checklists/level1/python/security.md",
    # "checklists/level1/python/mlops.md",
    "checklists/level1/general/platform.md",
    # "checklists/level1/general/qa.md",
    "checklists/level1/general/devsecops.md",
    "checklists/level1/general/data.md",
    "checklists/level1/java/platform.md",
    # "checklists/level1/java/integration.md",
    # "checklists/level1/java/qa.md",
    "checklists/level1/java/devsecops.md",
    # "checklists/level1/java/data.md",
    # "checklists/level1/java/general.md",
    # "checklists/level1/java/observability.md",
    # "checklists/level1/java/security.md",
    # "checklists/level1/csharp/api.md",
    "checklists/level1/csharp/platform.md",
    # "checklists/level1/csharp/integration.md",
    "checklists/level1/csharp/devtools.md",
    "checklists/level1/csharp/qa.md",
    "checklists/level1/csharp/devsecops.md",
    # "checklists/level1/csharp/data.md",
    # # "checklists/level1/csharp/general.md",
    # # "checklists/level1/csharp/backend.md",
    # # "checklists/level1/csharp/observability.md",
    # # "checklists/level1/csharp/frontend.md",
    # # "checklists/level1/csharp/mobile.md",
    # # "checklists/level1/csharp/security.md",
    "checklists/level1/csharp/mlops.md",
    "checklists/level1/javascript/platform.md",
    # "checklists/level1/javascript/integration.md",
    # "checklists/level1/javascript/qa.md",
    "checklists/level1/javascript/devsecops.md",
    # "checklists/level1/javascript/data.md",
    # "checklists/level1/javascript/general.md",
    # "checklists/level1/javascript/observability.md",
    # "checklists/level1/javascript/mobile.md",
    # "checklists/level1/javascript/security.md",
]

for file_path in FILES_TO_REMOVE:
    try:
        os.remove(file_path)
        print(f"Removed: {file_path}")
    except FileNotFoundError:
        print(f"Not found: {file_path}")
    except Exception as e:
        print(f"Error removing {file_path}: {e}")
